# Generated by Django 4.2.1 on 2023-05-04 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qualificationsname',
            new_name='Qualifications_name',
        ),
    ]
